/**
 * strings.js — every word the interface shows, in Brazilian Portuguese.
 *
 * One object, `t`, so a sentence exists in exactly one place: the tool
 * island's tooltip, the help dialog row and the hint line all read the same
 * tool name, and a future translation is a matter of swapping this file.
 * Functions are used where a string needs a value (counts, names).
 *
 * Plain JS on purpose (no JSX): the shortcut table and the editor actions
 * import it, and both run under `node --test`.
 */

export const t = Object.freeze({
  app: {
    name: 'Whiteboard',
    tagline: 'Um quadro branco colaborativo, desenhado à mão.',
  },

  /* --- tools (ids from editor/tools.js) -------------------------------- */
  tools: {
    hand: 'Mão (mover a tela)',
    select: 'Seleção',
    rect: 'Retângulo',
    diamond: 'Losango',
    ellipse: 'Elipse',
    arrow: 'Seta',
    line: 'Linha',
    pen: 'Desenho livre',
    text: 'Texto',
    image: 'Inserir imagem',
    eraser: 'Borracha',
    sticky: 'Nota adesiva',
    cylinder: 'Banco de dados',
  },
  toolIsland: {
    label: 'Ferramentas',
    lock: 'Manter a ferramenta ativa após desenhar',
    lockOn: 'Ferramenta travada (Q para destravar)',
    more: 'Mais ferramentas',
    library: 'Biblioteca',
    shortcut: (keys) => `Atalho: ${keys}`,
  },

  /* --- hint line under the tool island ---------------------------------- */
  hints: {
    shape: 'Clique e arraste, solte quando terminar. Shift mantém a proporção.',
    sticky: 'Clique para colocar uma nota adesiva e comece a digitar.',
    linear: 'Clique para marcar vários pontos, arraste para uma linha simples.',
    linearMulti: 'Clique para adicionar pontos. Enter, Esc ou clique duplo para terminar.',
    pen: 'Clique e arraste, solte quando terminar.',
    text: 'Dica: com a seleção, um clique duplo em qualquer lugar também cria texto.',
    eraser: 'Arraste sobre os elementos para apagar. Segure Alt para restaurar.',
    hand: 'Arraste para mover a tela. Ctrl + roda do mouse aproxima.',
    image: 'Escolha uma imagem para inserir no quadro.',
    editPoints: 'Clique duplo na linha para editar os pontos.',
    pointEditing: 'Arraste os pontos. Clique duplo num segmento adiciona um ponto; num ponto, remove (ou Delete). Esc para sair.',
    editText: 'Clique duplo ou Enter para editar o texto.',
    lockedElement: (keys) => `Elemento travado: ${keys} para destravar.`,
    lockedElements: (keys) => `Elementos travados: ${keys} para destravar.`,
    selection: 'Shift + clique soma à seleção. Alt + arrastar duplica.',
    locked: 'Ferramenta travada: ela continua ativa depois de cada desenho.',
  },

  /* --- main menu --------------------------------------------------------- */
  menu: {
    button: 'Menu',
    open: 'Abrir…',
    save: 'Salvar em arquivo',
    exportImage: 'Exportar imagem…',
    share: 'Compartilhar (copiar link)',
    clear: 'Limpar quadro',
    boards: 'Meus quadros',
    changeName: 'Alterar nome',
    themeDark: 'Tema escuro',
    themeLight: 'Tema claro',
    gridOn: 'Mostrar grade',
    gridOff: 'Ocultar grade',
    help: 'Ajuda',
    signedAs: (name) => `Você é ${name}`,
  },

  /* --- properties panel -------------------------------------------------- */
  props: {
    panel: 'Propriedades',
    toggle: 'Estilo',
    stroke: 'Traço',
    background: 'Fundo',
    fill: 'Preenchimento',
    strokeWidth: 'Espessura',
    strokeStyle: 'Estilo do traço',
    roughness: 'Traçado',
    roundness: 'Bordas',
    arrowheads: 'Pontas de seta',
    arrowStart: 'Início',
    arrowEnd: 'Fim',
    font: 'Fonte',
    fontSize: 'Tamanho',
    align: 'Alinhamento',
    opacity: 'Opacidade',
    layers: 'Camadas',
    actions: 'Ações',
    customColor: 'Cor personalizada',
    transparent: 'Transparente',
    mixed: 'Vários valores',
    colorName: (hex) => `Cor ${hex}`,
    fillStyles: { hachure: 'Hachurado', 'cross-hatch': 'Quadriculado', solid: 'Sólido', zigzag: 'Zigue-zague' },
    widths: { thin: 'Fino', bold: 'Médio', extraBold: 'Grosso' },
    strokeStyles: { solid: 'Contínuo', dashed: 'Tracejado', dotted: 'Pontilhado' },
    roughnessNames: { architect: 'Arquiteto', artist: 'Artista', cartoonist: 'Cartunista' },
    roundnessNames: { sharp: 'Retas', round: 'Arredondadas' },
    arrowheadNames: { none: 'Nenhuma', arrow: 'Seta', triangle: 'Triângulo', bar: 'Barra', dot: 'Ponto' },
    fontNames: { hand: 'À mão', normal: 'Normal', code: 'Código' },
    sizeNames: { S: 'Pequeno', M: 'Médio', L: 'Grande', XL: 'Muito grande' },
    alignNames: { left: 'Esquerda', center: 'Centro', right: 'Direita' },
  },

  /* --- element actions (panel, context menu, shortcuts) ----------------- */
  actions: {
    copy: 'Copiar',
    cut: 'Recortar',
    paste: 'Colar',
    duplicate: 'Duplicar',
    delete: 'Excluir',
    selectAll: 'Selecionar tudo',
    deselect: 'Limpar seleção',
    group: 'Agrupar',
    ungroup: 'Desagrupar',
    lock: 'Travar',
    unlock: 'Destravar',
    bringForward: 'Trazer para frente',
    sendBackward: 'Enviar para trás',
    bringToFront: 'Trazer para a frente de tudo',
    sendToBack: 'Enviar para trás de tudo',
    zoomIn: 'Aproximar',
    zoomOut: 'Afastar',
    resetZoom: 'Voltar para 100%',
    zoomToFit: 'Ajustar à tela',
    zoomToSelection: 'Ajustar à seleção',
    undo: 'Desfazer',
    redo: 'Refazer',
    editText: 'Editar texto',
    toggleGrid: 'Grade',
    toggleTheme: 'Alternar tema',
    exportImage: 'Exportar imagem',
    help: 'Ajuda',
    toggleToolLock: 'Travar ferramenta',
    nudge: 'Mover a seleção (Shift: 10×)',
    pan: 'Mover a tela (segure)',
    wheelZoom: 'Aproximar com a roda do mouse',
    escape: 'Fechar / cancelar / limpar seleção',
    save: 'Salvar em arquivo',
    open: 'Abrir arquivo',
  },

  /* --- feedback ----------------------------------------------------------- */
  toast: {
    copied: (n) => (n === 1 ? '1 elemento copiado' : `${n} elementos copiados`),
    cut: (n) => (n === 1 ? '1 elemento recortado' : `${n} elementos recortados`),
    nothingToPaste: 'Nada para colar',
    // Menu "Colar" where the browser will not let the page read the
    // clipboard (http origin, permission denied): the keyboard still works.
    pasteBlocked: (keys) =>
      keys
        ? `O navegador não deixou ler a área de transferência — use ${keys} para colar`
        : 'O navegador não deixou ler a área de transferência',
    pasteTruncated: (max) => `Texto colado cortado em ${Number(max).toLocaleString('pt-BR')} caracteres`,
    linkCopied: 'Link copiado — envie para quem vai desenhar com você',
    linkCopyFailed: 'Não foi possível copiar o link',
    saved: 'Arquivo salvo',
    opened: (n) => (n === 1 ? 'Arquivo aberto: 1 elemento' : `Arquivo aberto: ${n} elementos`),
    openFailed: 'Não foi possível abrir o arquivo',
    cleared: 'Quadro limpo — Ctrl+Z desfaz',
    imageFailed: 'Não foi possível inserir a imagem',
    exportFailed: 'Não foi possível exportar',
    pngCopied: 'Imagem copiada',
    pngCopyUnsupported: 'Este navegador não copia imagens; use Baixar',
    renamed: 'Quadro renomeado',
    renameFailed: 'Não foi possível renomear o quadro',
    rejected: 'Uma alteração foi recusada pelo servidor e foi desfeita.',
    nameChanged: (name) => `Agora você é ${name}`,
    dismiss: 'Fechar aviso',
  },

  /* --- top right ---------------------------------------------------------- */
  board: {
    untitled: 'Quadro sem título',
    renameHint: 'Clique para renomear',
    renameLabel: 'Nome do quadro',
    share: 'Compartilhar',
    peers: (n) => (n === 1 ? '1 pessoa no quadro' : `${n} pessoas no quadro`),
    you: 'você',
    alone: 'Só você está aqui. Compartilhe o link para desenhar junto.',
    more: (n) => `+${n}`,
    connection: {
      idle: 'Sem conexão',
      connecting: 'Conectando…',
      connected: 'Conectado — alterações ao vivo',
      offline: 'Offline — suas alterações serão enviadas ao reconectar',
      disconnected: 'Desconectado — tentando reconectar',
    },
  },

  /* --- footer -------------------------------------------------------------- */
  footer: {
    zoom: 'Zoom',
    zoomReset: (pct) => `${pct}% — clique para voltar a 100%`,
    history: 'Histórico',
    scrollBack: 'Voltar ao conteúdo',
  },

  /* --- welcome screen ------------------------------------------------------ */
  welcome: {
    title: 'Whiteboard',
    subtitle: 'Seus desenhos ficam salvos no servidor e aparecem ao vivo para quem tiver o link.',
    menuHint: 'Exportar, tema, grade e mais…',
    toolbarHint: 'Escolha uma ferramenta e comece a desenhar!',
    helpHint: 'Atalhos e ajuda',
    libraryHint: 'Formas prontas',
    open: 'Abrir arquivo',
    help: 'Atalhos e ajuda',
    library: 'Biblioteca de formas',
  },

  /* --- library ------------------------------------------------------------- */
  library: {
    title: 'Biblioteca',
    search: 'Buscar formas…',
    empty: 'Nenhuma forma encontrada.',
    hint: 'Clique para inserir no centro ou arraste para o quadro.',
    close: 'Fechar biblioteca',
    groups: { basic: 'Básico', shapes: 'Formas', notes: 'Notas', connectors: 'Conectores', diagrams: 'Diagramas' },
    items: {
      title: 'Título',
      text: 'Texto',
      box: 'Caixa',
      decision: 'Decisão',
      terminal: 'Início / fim',
      database: 'Banco de dados',
      sticky: 'Nota adesiva',
      container: 'Contêiner',
      arrow: 'Seta',
      line: 'Linha',
      process: 'Processo',
      person: 'Pessoa',
      yesNo: 'Sim / não',
    },
    content: {
      title: 'Título',
      text: 'Texto',
      box: 'Caixa',
      decision: 'Decisão?',
      terminal: 'Início',
      database: 'Dados',
      sticky: 'Nota',
      container: 'Grupo',
      step1: 'Etapa 1',
      step2: 'Etapa 2',
      step3: 'Etapa 3',
      person: 'Pessoa',
      yes: 'Sim',
      no: 'Não',
    },
  },

  /* --- dialogs -------------------------------------------------------------- */
  dialog: {
    close: 'Fechar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
  },
  help: {
    title: 'Atalhos de teclado',
    intro: 'Letras funcionam em qualquer layout de teclado. No Mac, Ctrl é ⌘.',
    groups: { tools: 'Ferramentas', edit: 'Edição', view: 'Visualizar', board: 'Quadro' },
    or: 'ou',
    footer: 'Tudo o que você desenha é salvo automaticamente e sincronizado ao vivo.',
  },
  export: {
    title: 'Exportar imagem',
    png: 'PNG',
    svg: 'SVG',
    background: 'Fundo',
    dark: 'Modo escuro',
    scale: 'Escala',
    onlySelected: 'Só a seleção',
    download: 'Baixar',
    copy: 'Copiar PNG',
    empty: 'O quadro está vazio — não há nada para exportar.',
    preview: 'Pré-visualização',
    rendering: 'Gerando…',
    size: (w, h) => `${w} × ${h} px`,
  },
  confirm: {
    clearTitle: 'Limpar o quadro?',
    clearMessage: 'Todos os elementos serão apagados para todos que estão no quadro. Você pode desfazer com Ctrl+Z.',
    clearConfirm: 'Limpar quadro',
    openTitle: 'Substituir o conteúdo?',
    openMessage: 'Abrir este arquivo substitui tudo o que está no quadro. Você pode desfazer com Ctrl+Z.',
    openConfirm: 'Abrir e substituir',
  },

  /* --- context menu ------------------------------------------------------- */
  contextMenu: { label: 'Ações do quadro' },

  /* --- nickname ------------------------------------------------------------- */
  nickname: {
    gateTitle: 'Como podemos te chamar?',
    gateText: 'Os quadros pertencem a uma pessoa, então a lista precisa saber de quem. Digite um nome e pronto.',
    label: 'Seu nome',
    placeholder: 'ex.: ana',
    hint: 'Sem conta e sem senha — é por este nome que seus quadros são encontrados.',
    errEmpty: 'Escolha um nome — a lista de quadros é filtrada por ele.',
    errLong: (n, max) => `Esse nome tem ${n} caracteres. Use no máximo ${max}.`,
    continue: 'Continuar',
    save: 'Salvar',
    cancel: 'Cancelar',
    change: 'Alterar nome',
    switcherText: 'Ao trocar de nome, a lista passa a mostrar os quadros do novo nome, além dos que ainda não têm dono.',
    setName: 'Definir nome',
  },

  /* --- board list ------------------------------------------------------------ */
  boards: {
    title: 'Meus quadros',
    subtitleEmpty: 'Um quadro branco compartilhado. Abra um para desenhar ou crie um novo.',
    subtitle: (mine, unclaimed) =>
      `${mine === 1 ? '1 seu' : `${mine} seus`}${unclaimed ? ` · ${unclaimed === 1 ? '1 sem dono' : `${unclaimed} sem dono`}` : ''}.`,
    subtitlePartial: (loaded, total) => `Mostrando ${loaded} de ${total} quadros (seus e sem dono).`,
    searchCount: (total, q) => (total === 1 ? `1 quadro com “${q}”.` : `${total} quadros com “${q}”.`),
    searching: 'Buscando…',
    searchLabel: 'Buscar quadros pelo nome',
    searchPlaceholder: 'Buscar quadros…',
    searchEmpty: (q) => `Nenhum quadro com “${q}”`,
    searchEmptyText: 'A busca procura no nome dos quadros que você vê nesta lista.',
    searchClear: 'Limpar busca',
    loadMore: (n) => (n > 0 ? `Carregar mais (${n} restantes)` : 'Carregar mais'),
    loadingMore: 'Carregando…',
    newBoard: 'Novo quadro',
    creating: 'Criando…',
    defaultTitle: 'Quadro sem título',
    copyTitle: (title) => `${title} (cópia)`,
    loadError: 'Não foi possível carregar seus quadros',
    loadErrorText: 'O servidor não respondeu.',
    retry: 'Tentar de novo',
    emptyTitle: (name) => `Nada aqui para ${name} ainda`,
    emptyText: 'Um quadro é uma tela compartilhada: desenhe formas, cole notas adesivas e convide outras pessoas para trabalhar junto, ao vivo.',
    emptyOwner: 'Tudo o que você criar aqui pertence a',
    emptyOtherName: 'Procurando um quadro criado com outro nome?',
    emptyChangeName: 'Altere seu nome',
    emptyOtherNameTail: '— quadros de outros nomes ficam ocultos de propósito.',
    firstBoard: 'Criar meu primeiro quadro',
    updated: (when) => `Atualizado ${when}`,
    rev: (n) => `rev. ${n}`,
    previewEmpty: 'Vazio',
    previewCount: (n) => `${Number(n).toLocaleString('pt-BR')} elementos`,
    unclaimed: 'Sem dono',
    unclaimedTitle: 'Ninguém é dono deste quadro ainda',
    claim: 'Assumir',
    claimLabel: (title) => `Assumir o quadro ${title}`,
    claimTitle: 'Tornar este quadro seu',
    claimed: (name) => `Quadro agora é de ${name}`,
    claimFailed: 'Não foi possível assumir o quadro',
    yours: 'seu',
    yoursTitle: 'Este quadro é seu',
    ownedBy: (owner) => `Pertence a ${owner}`,
    open: (title) => `Abrir ${title}`,
    rename: 'Renomear',
    renameLabel: (title) => `Renomear ${title}`,
    duplicate: 'Duplicar',
    duplicateLabel: (title) => `Duplicar ${title}`,
    delete: 'Excluir',
    deleteLabel: (title) => `Excluir ${title}`,
    confirmDelete: 'Excluir',
    cancelDelete: 'Cancelar exclusão',
    created: 'Quadro criado',
    createFailed: 'Não foi possível criar o quadro',
    renamed: 'Quadro renomeado',
    renameFailed: 'Não foi possível renomear o quadro',
    deleted: 'Quadro excluído',
    deleteFailed: 'Não foi possível excluir o quadro',
    duplicated: (title, n) =>
      n ? `Duplicado como “${title}” — ${n === 1 ? '1 elemento copiado' : `${n} elementos copiados`}` : `Duplicado como “${title}”`,
    duplicateFailed: 'Não foi possível duplicar o quadro',
    duplicateEmpty: (title) => `“${title}” foi criado, mas a cópia do conteúdo falhou. Abra-o e importe o original.`,
    time: {
      unknown: 'em data desconhecida',
      now: 'agora mesmo',
      minutes: (n) => `há ${n} min`,
      hours: (n) => `há ${n} h`,
      days: (n) => (n === 1 ? 'há 1 dia' : `há ${n} dias`),
    },
  },

  /* --- a board URL with no board behind it ---------------------------------------- */
  notFound: {
    title: 'Este quadro não existe',
    text: 'O link pode estar incompleto ou errado, ou o quadro foi excluído. Abra um dos seus quadros ou crie um novo.',
    deletedTitle: 'Este quadro não existe mais',
    deletedText: 'Ele foi excluído enquanto estava aberto (ou o servidor perdeu os quadros ao reiniciar). Nada do que for desenhado aqui pode ser salvo no servidor.',
    id: (id) => `Endereço procurado: ${id}`,
    save: (n) => (n === 1 ? 'Salvar o elemento na tela em arquivo' : `Salvar os ${n} elementos na tela em arquivo`),
    boards: 'Ir para Meus quadros',
  },

  /* --- errors ------------------------------------------------------------------ */
  errors: {
    title: 'Algo deu errado',
    message: 'Esta parte do quadro não pôde ser exibida. Suas alterações estão salvas no servidor — recarregar a página deve trazer tudo de volta.',
    canvasTitle: 'A área de desenho encontrou um problema',
    canvasMessage: 'O quadro não pôde ser desenhado, mas o resto do aplicativo continua funcionando. Recarregar costuma resolver; suas alterações estão salvas no servidor.',
    reload: 'Recarregar',
    retry: 'Tentar de novo',
    stack: 'Pilha de componentes',
    dismiss: 'Dispensar',
    /** Why a request failed, appended to a "Não foi possível …" (ui/errors.js). */
    reasons: {
      network: 'sem conexão com o servidor',
      boardGone: 'o quadro não existe mais',
      tooLarge: 'o conteúdo é grande demais',
      rateLimited: 'muitas tentativas seguidas; espere um pouco',
      server: 'erro no servidor',
    },
  },
});

export default t;
